# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8262e0b9ff9c312f73f8b7813d968ee5af133ceb03bdbc61ee5c23091e8fb1d92057524bfcdab5d288cc1bda35deb59284bdb146c20b188f7ffa70fd5bca46a9

test:
  secret_key_base: 4034199259f046b97f59bba9f0c6d553c70ffce3050e29b47ab4f5f0c19307f838d4eb3dafa876af406a81fc198afea924bb6c90581450968e7faebb58183217

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
